version: '3.1'

services: 
  postgres:
    image: postgres
    restart: always
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_DB=MANDE
      - POSTGRES_USER=marlon
      - POSTGRES_PASSWORD=admin123
    volumes:
      - ./postgres_data:/var/lib/postgresql/data


  pgadmin:
    image: dpage/pgadmin4
    environment:
     - PGADMIN_DEFAULT_EMAIL=marlon.anacona@correounivalle.edu.co
     - PGADMIN_DEFAULT_PASSWORD=root
    ports: 
      - 5050:80
    depends_on:
      -postgres
