version: "3.7"

services:
  nodebackend:
    build: .
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    environment:
      - EXTERNAL_PORT=8080
      - PGDATABASE=mande_db
      - PGUSER=marlon
      - PGPASSWORD=admin123
      - PGHOST=postgres
    volumes:
      - ./:/app/
      - /app/node_modules

  postgres:
    image: postgres:14
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=mande_db
      - POSTGRES_USER=marlon
      - POSTGRES_PASSWORD=admin123
    volumes:
      - ./1archivos.sql:/docker-entrypoint-initdb.d/1archivos.sql

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=marlon.anacona@correounivalle.edu.co
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80
    depends_on:
      - postgres
