version: "3.7"

services:
  nodebackend:
    build: .
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - ./:/app/
      - /app/node_modules

  postgres:
    image: postgres
    restart: always
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_DB=mande_db
      - POSTGRES_USER=marlon
      - POSTGRES_PASSWORD=admin123
    volumes:
      - ./prueba.sql:/docker-entrypoint-initdb.d/prueba.sql
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=marlon.anacona@correounivalle.edu.co
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80
    depends_on:
      - postgres
